// Daily Shmiras HaLashon learning schedule
// Based on the Chofetz Chaim Heritage Foundation's yearly learning program.
// Cycles through ~120 daily portions covering:
//   • Sefer Chafetz Chaim (Hilchot Lashon Hara + Hilchot Rechilut)
//   • Sefer Shmirat HaLashon (Sha'ar HaZechira + Sha'ar HaTevunah)
// One cycle repeats ~3 times per year, so the study is completed multiple times annually.

export interface ShlPortion {
  portionNumber: number; // 1–120
  title: string;         // Short title shown on the checklist
  description: string;   // What to learn today
  sefariaRef?: string;   // Sefaria search hint (title only, not a direct URL)
}

const SHL_PORTIONS: ShlPortion[] = [
  // ── SEFER CHAFETZ CHAIM — Hilchot Lashon Hara ─────────────────────────────
  // Introduction (Petichah)
  { portionNumber: 1,  title: "CC — Petichah (1): The Two Mitzvot",         description: "Introduction: the positive commandment to guard your speech and the prohibition against speaking lashon hara. Why the Torah uses the word 'lech' (go) regarding the spies.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 2,  title: "CC — Petichah (2): The 31 Prohibitions",     description: "Overview of the 31 negative commandments violated by speaking lashon hara — including geneivat da'at, ona'at devarim, and shaming another person.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 3,  title: "CC — Petichah (3): The 14 Positive Duties",  description: "The 14 positive mitzvot to love your neighbor, judge favorably, and preserve another's life — all of which are related to guarding speech.", sefariaRef: "Chofetz Chaim" },

  // Hilchot Lashon Hara — Positive Commandments
  { portionNumber: 4,  title: "CC — LH Positive §1: The Core Prohibition",  description: "The biblical prohibition against lashon hara (Vayikra 19:16). Definition: any derogatory speech about a fellow Jew that is true. Motzi shem ra (false speech) is far worse.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 1" },
  { portionNumber: 5,  title: "CC — LH Positive §2: In Public",             description: "Lashon hara spoken before three or more people is even more severe — the listeners will spread it and it becomes impossible to retract. The prohibition applies regardless of audience size.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 2" },
  { portionNumber: 6,  title: "CC — LH Positive §3: About Scholars",        description: "Lashon hara about a Torah scholar carries extra severity. Even trivial criticism of a talmid chacham is treated as a grave transgression against Torah itself.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 3" },
  { portionNumber: 7,  title: "CC — LH Positive §4: About Deceased",        description: "The prohibition against lashon hara applies even to those who have died. Shaming the deceased is a terrible act — they cannot defend themselves or do teshuvah.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 4" },
  { portionNumber: 8,  title: "CC — LH Positive §5: About Oneself",         description: "Speaking degradingly about oneself (in a context where it will cause others to mock or disrespect you) is also prohibited — it can lead to disrespecting one's family.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 5" },
  { portionNumber: 9,  title: "CC — LH Positive §6: Implied Lashon Hara",   description: "Lashon hara can be conveyed through hints, facial expressions, or faint praise ('what can I say about so-and-so...'). All implied forms are equally prohibited.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 6" },
  { portionNumber: 10, title: "CC — LH Positive §7: Written Lashon Hara",   description: "Writing derogatory information about a person violates the prohibition no less than speaking it — perhaps more, since written words spread further and last longer.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 7" },
  { portionNumber: 11, title: "CC — LH Positive §8: True but Harmful",       description: "A statement that is completely true but will cause the subject to be despised or lose money is still lashon hara. The test is the effect, not the accuracy.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 8" },
  { portionNumber: 12, title: "CC — LH Positive §9: Lashon Hara on Groups", description: "Derogatory speech about an entire community, city, or family is prohibited. One who insults a family or community insults every member within it.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 9" },
  { portionNumber: 13, title: "CC — LH Positive §10: Comparing Unfavorably", description: "Praising one person in front of their rival in a way that implies criticism of the rival is indirect lashon hara — the praise itself becomes the vehicle of harm.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 10" },
  { portionNumber: 14, title: "CC — LH Positive §11: Rechilut Context",      description: "Information shared with the intent of causing conflict between two people — even when true — falls under rechilut. Intent determines the category of forbidden speech.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 11" },
  { portionNumber: 15, title: "CC — LH Positive §12: The Five Exceptions",   description: "Five conditions under which reporting negative information is permitted (l'toelet — for a constructive purpose): intent to protect, no exaggeration, prior rebuke, no alternative, no additional harm caused.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 12" },
  { portionNumber: 16, title: "CC — LH Positive §13: Protecting from Harm",  description: "One is permitted — indeed obligated — to warn someone of impending harm even if it requires revealing negative information. 'Do not stand by your neighbor's blood' (Vayikra 19:16).", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 13" },
  { portionNumber: 17, title: "CC — LH Positive §14: Shidduch Inquiries",    description: "When asked about a potential spouse or business partner, one may and must share relevant negative information — under strict conditions. Withholding critical information can cause great harm.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara 14" },

  // Hilchot Lashon Hara — Negative Commandments (Prohibitions)
  { portionNumber: 18, title: "CC — LH Negative §1: Do Not Bear Tales",      description: "The prohibition against rechilut: 'Do not go as a talebearer among your people' (Vayikra 19:16). Even true information that sows discord is forbidden.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 1" },
  { portionNumber: 19, title: "CC — LH Negative §2: Do Not Hate in Heart",   description: "'You shall not hate your brother in your heart' (Vayikra 19:17). Harboring silent grudges is a sin — one must rebuke, resolve, and release resentment.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 2" },
  { portionNumber: 20, title: "CC — LH Negative §3: Do Not Shame Others",    description: "The prohibition against publicly embarrassing a person. 'It is better to be thrown into a furnace than to shame another in public' (Berakhot 43b). Related to murder in severity.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 3" },
  { portionNumber: 21, title: "CC — LH Negative §4: Do Not Take Revenge",    description: "'You shall not take revenge' (Vayikra 19:18). Even revenge through words alone — 'I won't help you since you didn't help me' — is biblically forbidden.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 4" },
  { portionNumber: 22, title: "CC — LH Negative §5: Do Not Bear a Grudge",   description: "'You shall not bear a grudge' (Vayikra 19:18). Even if you help the person who wronged you while mentally noting the past — this is bearing a grudge.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 5" },
  { portionNumber: 23, title: "CC — LH Negative §6: Do Not Oppress",         description: "'You shall not oppress your fellow' (Vayikra 25:17) — interpreted as prohibiting verbal oppression (ona'at devarim): reminding someone of past sins or mistakes.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 6" },
  { portionNumber: 24, title: "CC — LH Negative §7: Do Not Curse Others",    description: "The prohibition against cursing a fellow Jew — even in one's heart. A curse said privately with full intent may have real spiritual consequences.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 7" },
  { portionNumber: 25, title: "CC — LH Negative §8: Do Not Curse Parents",   description: "An additional prohibition against cursing one's parents — distinct from the general prohibition and carrying a more severe consequence in biblical law.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 8" },
  { portionNumber: 26, title: "CC — LH Negative §9: Do Not Curse the Deaf",  description: "The prohibition against cursing the deaf (Vayikra 19:14) — interpreted broadly: even one who cannot defend themselves or respond must be protected from verbal abuse.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 9" },
  { portionNumber: 27, title: "CC — LH Negative §10: Do Not Accept LH",      description: "The prohibition against listening to and believing lashon hara — 'do not raise a false report' (Shemot 23:1). One may listen to it cautiously but must not believe it as fact.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 10" },
  { portionNumber: 28, title: "CC — LH Negative §11: Do Not Flatter",        description: "The prohibition against flattery (chanifah) — praising the wicked or telling a sinner that their conduct is acceptable. Flattery in court causes injustice; in daily life it corrupts character.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 11" },
  { portionNumber: 29, title: "CC — LH Negative §12: False Testimony",        description: "The prohibition against false testimony in any context — including exaggerating the truth in one's favor or omitting crucial facts.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 12" },
  { portionNumber: 30, title: "CC — LH Negative §13: Joining Wrongdoers",    description: "The prohibition against associating with or lending support to those who commit public sins — 'do not follow a multitude to do evil' (Shemot 23:2).", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 13" },
  { portionNumber: 31, title: "CC — LH Negative §14: Frivolous Oaths",       description: "The prohibition against swearing by God's name frivolously — this includes excessive speech that trivializes holy things and leads to oaths being taken lightly.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 14" },
  { portionNumber: 32, title: "CC — LH Negative §15: Speaking in Anger",     description: "The prohibition against speech driven by anger and the Torah's command to be slow to anger. Angry speech almost always contains elements of shaming, exaggeration, or falsehood.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 15" },
  { portionNumber: 33, title: "CC — LH Negative §16: Indecent Speech",       description: "The prohibition against nivul peh (obscene speech) — it degrades the speaker's soul and corrupts the atmosphere. The mouth is the instrument of Torah; it must be kept holy.", sefariaRef: "Chofetz Chaim, Hilchot Lashon Hara, Laav 16" },
  { portionNumber: 34, title: "CC — LH Negative §17: Summary & Chazara",     description: "Review of the 17 negative commandments of Hilchot Lashon Hara. Reflect: which of these am I most at risk for? What can I do differently this week?", sefariaRef: "Chofetz Chaim" },

  // Hilchot Rechilut — Positive Commandments
  { portionNumber: 35, title: "CC — Rechilut Positive §1: What is Rechilut?", description: "Definition of rechilut (tale-bearing): relaying information to person A about what person B said about them, causing conflict — even if the information is 100% true and accurate.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 1" },
  { portionNumber: 36, title: "CC — Rechilut Positive §2: Implied Rechilut",  description: "Rechilut can be communicated through hints, through 'I'm not going to tell you what so-and-so said about you,' or through facial expressions. All forms are prohibited.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 2" },
  { portionNumber: 37, title: "CC — Rechilut Positive §3: When Permitted",    description: "Rechilut is permitted only to prevent harm — e.g., warning someone that a business partner plans to cheat them. The five conditions from lashon hara apply here as well.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 3" },
  { portionNumber: 38, title: "CC — Rechilut Positive §4: About Scholars",    description: "Rechilut involving a Torah scholar is treated with the same severity as lashon hara about a scholar — extra care is required when the subject has elevated status.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 4" },
  { portionNumber: 39, title: "CC — Rechilut Positive §5: Listener's Duty",   description: "One who hears rechilut is obligated not to believe it, not to respond negatively to the subject, and ideally to reprove the speaker. Passive listening encourages the sin.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 5" },
  { portionNumber: 40, title: "CC — Rechilut Positive §6: Causing Enemies",   description: "One of the greatest harms of rechilut is manufacturing enemies where there were none. The talebearer's words can permanently destroy a relationship that would otherwise have healed.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 6" },
  { portionNumber: 41, title: "CC — Rechilut Positive §7: Telling the Truth", description: "Even if what is relayed is completely accurate and well-intentioned, rechilut is forbidden if it will cause the listener to despise the subject. The test is the effect, not the intent.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 7" },
  { portionNumber: 42, title: "CC — Rechilut Positive §8: Between Spouses",   description: "Rechilut between husband and wife — reporting to a spouse what others said about them — is especially damaging to shalom bayit. It should be avoided even when no ill intent is present.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 8" },
  { portionNumber: 43, title: "CC — Rechilut Positive §9: Summary & Review",  description: "Review all nine sections of Hilchot Rechilut. Rechilut is the midwife of machlokes (conflict). Where there is strife, there is almost always a talebearer at its source.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut 9" },

  // Hilchot Rechilut — Negative Commandments
  { portionNumber: 44, title: "CC — Rechilut Negative §1–3: The Core Sins",   description: "The three core prohibitions unique to rechilut: (1) 'Do not go as a talebearer' (Vayikra 19:16), (2) the prohibition of hatred that follows, (3) causing the listener to sin.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut, Laav 1-3" },
  { portionNumber: 45, title: "CC — Rechilut Negative §4–7: Indirect Forms",  description: "Indirect rechilut through writing, through involving a third party, through provoking the listener to investigate. Every method of causing conflict through information is covered.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut, Laav 4-7" },
  { portionNumber: 46, title: "CC — Rechilut Negative §8–10: Listener's Sin", description: "The prohibition against listening to rechilut and forming conclusions. The listener who investigates based on rechilut, or who acts on the information, is a separate sinner.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut, Laav 8-10" },
  { portionNumber: 47, title: "CC — Rechilut Negative §11–14: Final Review",  description: "Final four prohibitions and a comprehensive review of Hilchot Rechilut. Resolve: I will be a peacemaker rather than a talebearer. I will mention no one's name in a negative context today.", sefariaRef: "Chofetz Chaim, Hilchot Rechilut, Laav 11-14" },

  // ── SEFER SHMIRAT HALASHON — Sha'ar HaZechira ──────────────────────────────
  { portionNumber: 48, title: "SHL — Sha'ar HaZechira, Ch. 1: Introduction",  description: "The first gate of Sefer Shmirat HaLashon: why God gave us the power of speech, and how this most divine of gifts is simultaneously the most dangerous.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 49, title: "SHL — Sha'ar HaZechira, Ch. 2: Creation",      description: "Man was created last on the sixth day to receive the gift of speech as a crown. Speech distinguishes us from animals and connects us to the Divine. Misusing it inverts the purpose of creation.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 50, title: "SHL — Sha'ar HaZechira, Ch. 3: The Spies",    description: "The story of the meraglim (spies) as the paradigmatic sin of lashon hara. An entire generation lost its portion in the Land because of the sin of speech.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 51, title: "SHL — Sha'ar HaZechira, Ch. 4: Miriam",       description: "Miriam spoke about her brother Moshe and was struck with tzaraat immediately. If Miriam — a prophetess who spoke with the best intentions — was punished thus, how much more so must we be careful!", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 52, title: "SHL — Sha'ar HaZechira, Ch. 5: Tzaraat",      description: "The disease of tzaraat was a supernatural warning against lashon hara. When the Temple stood, the metzora was sent outside the camp to reflect on the harm caused by his speech.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 53, title: "SHL — Sha'ar HaZechira, Ch. 6: King David",   description: "David HaMelech's Tehillim are filled with pleas to guard his tongue. 'Who is the man who desires life — guard your tongue from evil and your lips from speaking deceit' (Ps. 34:13-14).", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 54, title: "SHL — Sha'ar HaZechira, Ch. 7: Poverty",      description: "The Talmud teaches that lashon hara causes poverty. The mouth that brings blessing and prayer to God must not simultaneously be used to drag another person down.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 55, title: "SHL — Sha'ar HaZechira, Ch. 8: Punishment",   description: "The Midrash describes the punishment for lashon hara in the World to Come. But the greater concern is the damage in this world: destroyed families, lost livelihoods, broken communities.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 56, title: "SHL — Sha'ar HaZechira, Ch. 9: Prayer",       description: "Lashon hara blocks our prayers from being accepted. How can we ask God to judge us mercifully if we judge our fellow harshly? The two courts — divine and human — mirror each other.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 57, title: "SHL — Sha'ar HaZechira, Ch. 10: Shabbat",     description: "On Shabbat, when our neshamah yeteirah (extra soul) is present, we are especially capable of Torah conversation. Shabbat table talk that degrades others wastes this sacred opportunity.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 58, title: "SHL — Sha'ar HaZechira, Ch. 11: The Tongue",  description: "Physical description of the tongue: surrounded by two walls (teeth and lips) — hints that it requires double protection. Speech is the only instrument that can sin while the body is motionless.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 59, title: "SHL — Sha'ar HaZechira, Ch. 12: The Walls",   description: "The teeth (bone) and lips (flesh) are designed as gatekeepers of speech. One who speaks recklessly breaks down both walls and exposes the most dangerous instrument of destruction.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 60, title: "SHL — Sha'ar HaZechira, Ch. 13: Gossip",      description: "The social context of lashon hara: the gathering, the dinner table, the study hall. Places where people congregate create the greatest temptation for forbidden speech.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 61, title: "SHL — Sha'ar HaZechira, Ch. 14: The Listener", description: "The one who listens to lashon hara enables the speaker. Three parties are harmed by lashon hara: the speaker, the listener, and the subject. The listener's sin is sometimes greater than the speaker's.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 62, title: "SHL — Sha'ar HaZechira, Ch. 15: Teshuvah",    description: "Can one do full teshuvah for lashon hara? Unlike theft or physical harm, repairing the damage of speech is nearly impossible — words once spoken cannot be retrieved. Teshuvah requires extraordinary effort.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 63, title: "SHL — Sha'ar HaZechira, Ch. 16: Yom Kippur",  description: "On Yom Kippur we confess many speech-related sins (dibarnu, nirgannu, etc.) — more sins of speech appear in the viduy than any other category. This reflects the pervasive nature of the sin.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 64, title: "SHL — Sha'ar HaZechira, Ch. 17: Apology",     description: "When we harm someone through speech, we must ask their forgiveness directly. This is more difficult than returning stolen property — one can return an object but not recalled words.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 65, title: "SHL — Sha'ar HaZechira, Ch. 18: Machlokes",   description: "Conflict (machlokes) is almost always seeded by forbidden speech. A single piece of rechilut can destroy a kehillah. Shalom (peace) is so important that the Torah permitted certain falsehoods to preserve it.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 66, title: "SHL — Sha'ar HaZechira, Ch. 19: Honesty",     description: "The trait of emet (truth) is foundational to guarding speech. One who trains themselves to speak only truth will naturally avoid lashon hara, flattery, and empty promises.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 67, title: "SHL — Sha'ar HaZechira, Ch. 20: Study Halls", description: "Even in the beit midrash, speech can become corrupted — through mockery of other scholars, competitive put-downs, or dismissing another's learning. A place of Torah demands the highest standard.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 68, title: "SHL — Sha'ar HaZechira, Ch. 21: Business",    description: "Business settings create constant pressure to speak negatively — about competitors, colleagues, customers. The Chofetz Chaim addresses this environment directly with practical guidance.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 69, title: "SHL — Sha'ar HaZechira, Ch. 22: Family",      description: "The home is where speech habits are formed and transmitted to the next generation. Parents who speak lashon hara at the Shabbos table teach their children to do the same.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 70, title: "SHL — Sha'ar HaZechira, Ch. 23: The Power of Words", description: "Words shape reality. Blessing and curse both operate through speech. The Talmud records that rabbinic curses — even uttered conditionally — took effect. Guard your words accordingly.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 71, title: "SHL — Sha'ar HaZechira, Ch. 24: Positive Speech", description: "The antidote to lashon hara is cultivating positive speech: praise for others, words of Torah, encouragement, and blessing. Every conversation is an opportunity to build rather than destroy.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 72, title: "SHL — Sha'ar HaZechira, Ch. 25: The Three",   description: "Three people are harmed by each act of lashon hara: the speaker (spiritually), the listener (who is drawn into sin), and the subject (whose reputation suffers). All three suffer consequences.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 73, title: "SHL — Sha'ar HaZechira, Ch. 26: Daily Guard", description: "Practical strategies for guarding speech daily: speaking less rather than more, thinking before speaking, redirecting conversations that drift into forbidden territory.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 74, title: "SHL — Sha'ar HaZechira, Ch. 27: The Exam",    description: "An accounting: how many times did I speak lashon hara today? The Chofetz Chaim suggests that most people sin in this area dozens of times daily without realizing it.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 75, title: "SHL — Sha'ar HaZechira, Ch. 28: Silence",     description: "The Talmud says silence is the best safeguard. One who speaks only when necessary will rarely sin in speech. The path to purity of speech begins with training yourself to be comfortable with silence.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 76, title: "SHL — Sha'ar HaZechira, Ch. 29: Legacy",      description: "The legacy of the Chofetz Chaim himself — who transformed Jewish awareness of the laws of lashon hara through his life's work. His books, his conduct, and his personal example.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 77, title: "SHL — Sha'ar HaZechira, Ch. 30: Summary",     description: "Final review of Sha'ar HaZechira. Resolve: I will make a specific kabbalah (commitment) regarding my speech this week — one practical change I will implement.", sefariaRef: "Shmirat HaLashon" },

  // ── SEFER SHMIRAT HALASHON — Sha'ar HaTevunah ──────────────────────────────
  { portionNumber: 78,  title: "SHL — Sha'ar HaTevunah, Ch. 1: Introduction", description: "The second gate of Sefer Shmirat HaLashon — the Gate of Understanding. The intellectual and philosophical foundations for why guarding speech is the most transformative practice.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 79,  title: "SHL — Sha'ar HaTevunah, Ch. 2: Free Will",    description: "God gave us free will specifically regarding speech — we choose every word we say. This makes every choice of silence a great act, and every reckless word a free choice to sin.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 80,  title: "SHL — Sha'ar HaTevunah, Ch. 3: Divine Speech", description: "God created the world through speech (Bereishit Rabbah). Human speech — created in His image — therefore carries creative and destructive power beyond what we perceive.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 81,  title: "SHL — Sha'ar HaTevunah, Ch. 4: The Neshamah", description: "The soul is connected to God through the channel of speech. Torah study, prayer, and blessing all operate through speech. Corrupting this channel damages the soul's connection to its source.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 82,  title: "SHL — Sha'ar HaTevunah, Ch. 5: Middot",       description: "The character traits that guard or undermine speech: humility prevents one from putting others down; patience prevents angry speech; generosity prevents jealous speech.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 83,  title: "SHL — Sha'ar HaTevunah, Ch. 6: Ahavat Yisrael", description: "Love of one's fellow Jew is the opposite of lashon hara. When you truly love someone, you cannot speak ill of them. Building ahavat Yisrael is the most powerful protection against forbidden speech.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 84,  title: "SHL — Sha'ar HaTevunah, Ch. 7: Dan Lekaf Zechut", description: "Judging others favorably (dan lekaf zechut) is both a mitzvah and a speech protection. When you assume the best about people, you have nothing negative to report.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 85,  title: "SHL — Sha'ar HaTevunah, Ch. 8: Humility",     description: "The humble person does not need to raise themselves by lowering others. Arrogance is the root cause of most lashon hara — the desire to feel superior by exposing others' flaws.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 86,  title: "SHL — Sha'ar HaTevunah, Ch. 9: Patience",     description: "Anger is the breeding ground of forbidden speech. When we are provoked, the tongue becomes the weapon. Practicing patience removes the trigger that fires the weapon.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 87,  title: "SHL — Sha'ar HaTevunah, Ch. 10: Contentment", description: "Jealousy drives much gossip — we speak negatively about those who have what we lack. Cultivating satisfaction with one's own portion removes the jealousy that fuels harmful speech.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 88,  title: "SHL — Sha'ar HaTevunah, Ch. 11: Emunah",      description: "Faith in Divine Providence means accepting that whatever happens to us is from God — including insults and slights from others. One who truly believes this has no need for revenge or resentment.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 89,  title: "SHL — Sha'ar HaTevunah, Ch. 12: Torah Study", description: "Torah study purifies speech. One who spends time in Torah naturally speaks in the language of Torah — words of wisdom, encouragement, and teaching rather than gossip.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 90,  title: "SHL — Sha'ar HaTevunah, Ch. 13: Tefillah",    description: "Prayer is the bridge between human speech and divine speech. One who prays deeply and honestly calibrates their speech toward holiness — they become less able to corrupt the instrument of prayer.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 91,  title: "SHL — Sha'ar HaTevunah, Ch. 14: Tzedakah",    description: "Giving generously counters the selfishness that drives most forbidden speech. The generous person cares about others' well-being and naturally avoids harming them through words.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 92,  title: "SHL — Sha'ar HaTevunah, Ch. 15: Shabbat",     description: "Shabbat is the ideal time to recalibrate speech — no business pressures, family gathered, Torah learning at its peak. Shabbat conversations should be elevated above weekday patterns.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 93,  title: "SHL — Sha'ar HaTevunah, Ch. 16: Children",    description: "Teaching children to guard their speech — the most important chinuch investment. Children who learn to speak carefully become adults who create peace rather than conflict.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 94,  title: "SHL — Sha'ar HaTevunah, Ch. 17: Community",   description: "A community whose members guard their speech becomes a sanctuary of peace. Shuls and schools that enforce speech standards create environments where Torah can truly flourish.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 95,  title: "SHL — Sha'ar HaTevunah, Ch. 18: The Courts",  description: "Jewish courts that operate with truthful testimony and careful speech are divinely assisted. A beit din where lashon hara is spoken loses its legitimacy as a vehicle for divine justice.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 96,  title: "SHL — Sha'ar HaTevunah, Ch. 19: The Long Run", description: "People who guard their speech consistently report a transformation over time: relationships improve, business prospers, and they feel spiritually lighter. The reward is tangible.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 97,  title: "SHL — Sha'ar HaTevunah, Ch. 20: The Scale",   description: "A person who sins once in lashon hara can repent and recover. One who makes it a habit — who speaks lashon hara dozens of times daily — is in serious spiritual danger.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 98,  title: "SHL — Sha'ar HaTevunah, Ch. 21: Priorities",  description: "When the choice is between speaking and remaining silent in any ambiguous situation, always choose silence. The cost of unnecessary speech is almost always higher than its benefit.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 99,  title: "SHL — Sha'ar HaTevunah, Ch. 22: The Daily Test", description: "A practical accounting of your speech today. Were your words truthful? Necessary? Kind? Would you be comfortable if the subject overheard everything you said about them?", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 100, title: "SHL — Sha'ar HaTevunah, Ch. 23: Rebuke",      description: "Proper rebuke (tochachah) — given privately, gently, with love — is the antidote to both sin and to the need for rechilut. Problems addressed directly require no intermediary tale-bearer.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 101, title: "SHL — Sha'ar HaTevunah, Ch. 24: Shalom",      description: "Peace is the vessel that contains all blessing. Every moment spent making peace is more valuable than all the benefits of speaking. Become a rodef shalom — a pursuer of peace.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 102, title: "SHL — Sha'ar HaTevunah, Ch. 25: Reward",      description: "The reward for guarding one's speech: long life (as promised in Psalm 34), good relationships, answered prayers, and a portion in the World to Come alongside those who bring peace.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 103, title: "SHL — Sha'ar HaTevunah, Ch. 26: Conclusion",  description: "Final chapter: the life of one who has truly internalized these lessons. Their home is peaceful, their prayers are answered, their words carry the weight of truth and holiness.", sefariaRef: "Shmirat HaLashon" },

  // ── CHAZARA (Review Cycle) ─────────────────────────────────────────────────
  { portionNumber: 104, title: "Review: The 14 Positive Duties",              description: "Chazara — review the 14 positive mitzvot related to guarding speech: love your neighbor, rebuke properly, judge favorably, pursue peace, and protect others from harm.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 105, title: "Review: Definitions — LH vs. Rechilut",       description: "Distinguish lashon hara (derogatory speech) from rechilut (tale-bearing). Both are prohibited; both cause harm. Lashon hara harms the subject's reputation; rechilut manufactures conflict.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 106, title: "Review: The Five Conditions for L'Toelet",    description: "The five conditions required before sharing negative information for a constructive purpose: (1) accurate, (2) not exaggerated, (3) proper intent, (4) no alternative, (5) proportionate harm.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 107, title: "Review: Listening as Sin",                    description: "The prohibition against listening to and accepting lashon hara. Review: what is the correct response when someone begins telling you forbidden information about another person?", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 108, title: "Review: Business Speech",                     description: "Practical review: speech hazards in business. Disparaging a competitor, exaggerating one's product's quality, blaming an employee publicly, spreading rumors about a company.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 109, title: "Review: Family Speech",                       description: "Practical review: speech hazards at home. Speaking negatively about one spouse to the other's family, criticizing in-laws, embarrassing children in front of guests.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 110, title: "Review: Social Speech",                       description: "Practical review: speech hazards in social settings. The Shabbos table, the kiddush, the carpool, the WhatsApp group — all are high-risk environments for forbidden speech.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 111, title: "Review: The Listener's Obligations",          description: "A review of what to do when you are on the receiving end of forbidden speech: signal your discomfort, refuse to believe the negative information, and redirect the conversation.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 112, title: "Review: Flattery (Chanifah)",                 description: "Flattery is the shadow of lashon hara — instead of tearing others down, the flatterer builds up falsely. Both corrupt truth. Review the prohibition of chanifah and its practical applications.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 113, title: "Review: Implied and Written Speech",          description: "Review: lashon hara through hints, facial expressions, writing, and social media. These forms are fully prohibited — sometimes more severe than spoken words due to their permanence.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 114, title: "Review: Teshuvah for Speech Sins",            description: "The path of teshuvah for having spoken lashon hara. Verbally retract the statement, inform the listener it was wrong to say, approach the subject for forgiveness where possible.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 115, title: "Review: Sha'ar HaZechira Highlights",         description: "Review of the top ten insights from Sha'ar HaZechira: the stories of the spies, Miriam, the connection to poverty, prayer, and the legacy of the Chofetz Chaim himself.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 116, title: "Review: Sha'ar HaTevunah Highlights",         description: "Review of the top ten middot that protect speech: humility, patience, contentment, emunah, ahavat Yisrael, dan lekaf zechut, Torah study, tefillah, tzedakah, shalom.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 117, title: "Making a Kabbalah: Speech Commitment",        description: "Choose ONE specific speech improvement to take on for the coming week: e.g., 'I will not discuss any named person in a negative way.' Write it down. Review it each morning.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 118, title: "The Bigger Picture: Kavod HaBriot",           description: "All the laws of speech ultimately rest on one foundation: every person is created in the image of God (tzelem Elokim) and deserves dignity. Lashon hara is an assault on that dignity.", sefariaRef: "Chofetz Chaim" },
  { portionNumber: 119, title: "The Goal: Bringing Peace to the World",       description: "The Talmud says the world was created for the sake of peace (Gittin 59b). Every act of careful speech is a building block of the peaceful world that Torah envisions.", sefariaRef: "Shmirat HaLashon" },
  { portionNumber: 120, title: "Completion & Beginning Again",                description: "You have completed one full cycle of Shmiras HaLashon study. Like Talmud Torah, the real study begins on the second cycle. Begin again tomorrow — deeper, wiser, and more committed.", sefariaRef: "Chofetz Chaim" },
];

/**
 * Returns today's Shmiras HaLashon portion based on the day of year (mod 120).
 * The cycle starts fresh on January 1 each year, cycling through all 120 portions
 * approximately 3 times per year.
 */
export function getShlPortion(): ShlPortion {
  const now = new Date();
  const startOfYear = new Date(now.getFullYear(), 0, 1);
  const dayOfYear = Math.floor((now.getTime() - startOfYear.getTime()) / 86_400_000);
  const idx = dayOfYear % SHL_PORTIONS.length;
  return SHL_PORTIONS[idx];
}

export function useShmiras(): ShlPortion {
  return getShlPortion();
}
